version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
      args:
        config: nginx.conf
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"

  backend:
    build:
      context: './'
      dockerfile: './packages/server/Dockerfile'
    environment:
      - NODE_ENV=development
      - CLIENT_PORT=8080
      - SERVER_PORT=3000
      - FREESOUND_CLIENT_ID=${FREESOUND_CLIENT_ID}
      - FREESOUND_CLIENT_SECRET=${FREESOUND_CLIENT_SECRET}
    ports:
      - "3000:3000"

  frontend:
    build:
      context: './'
      dockerfile: './packages/client/Dockerfile'
    environment:
      - NODE_ENV=development
      - VITE_CLIENT_PORT=8080
      - VITE_SERVER_PORT=3000
    ports:
      - "8080:8080"
